Repository takahirox/three-gltf-extensions, pull requests merged in 2021-02, with the labels that each got.

#1 Loader: Add KHR_materials_variants
  examples/KHR_materials_variants.html
  examples/assets/gltf/MaterialsVariantsShoe/README.md
  examples/assets/gltf/MaterialsVariantsShoe/glTF/MaterialsVariantsShoe.bin
  examples/assets/gltf/MaterialsVariantsShoe/glTF/MaterialsVariantsShoe.gltf
  examples/assets/gltf/MaterialsVariantsShoe/glTF/diffuseBeach.jpg
  examples/assets/gltf/MaterialsVariantsShoe/glTF/diffuseMidnight.jpg
  examples/assets/gltf/MaterialsVariantsShoe/glTF/diffuseStreet.jpg
  examples/assets/gltf/MaterialsVariantsShoe/glTF/normal.jpg
  examples/assets/gltf/MaterialsVariantsShoe/glTF/occlusionRougnessMetalness.jpg
  examples/assets/gltf/MaterialsVariantsShoe/screenshot/screenshot.jpg
  examples/assets/textures/equirectangular/quarry_01_1k.hdr
  examples/libs/dat.gui.module.js
  examples/main.css
  examples/three/controls/OrbitControls.js
  examples/three/loaders/GLTFLoader.js
  examples/three/loaders/RGBELoader.js
  examples/three/three.module.js
  examples/utils/copy_js.sh
  exporters/README.md
  loaders/KHR_materials_variants/README.md
  loaders/KHR_materials_variants/plugin.js
  loaders/README.md
Labels: enhancement

#19 Fixed GLTFTextureDDSExtension example
  loaders/MSFT_texture_dds/README.md
Labels: documentation

#24 KHR_materials_variants Loader plugin: selectVariant() accepts null variant name to select original materials
  loaders/KHR_materials_variants/KHR_materials_variants.js
  loaders/KHR_materials_variants/README.md
Labels: enhancement

#25 Tests: Add selectVariant() and ensureLoadVariantMaterials() unit tests
  loaders/KHR_materials_variants/KHR_materials_variants.js
  test/KHR_materials_variants.js
Labels: test

#26 Fix ensureLoadVariants() name mismatch between readme and others
  examples/KHR_materials_variants.html
  exporters/KHR_materials_variants/README.md
  loaders/KHR_materials_variants/KHR_materials_variants.js
  test/KHR_materials_variants.js
Labels: bug

#27 Add MSFT_texture_dds loader plugin unit test
  test/MSFT_texture_dds.js
Labels: test

#31 Examples: Improve index.html for thin screen
  examples/ic_menu_black_24dp.svg
  examples/index.css
  examples/index.html
Labels: examples

#33 EXT_text: Return null, not Promise, from createNodeAttachment() if no extension in node
  loaders/EXT_text/EXT_text.js
Labels: bug

#34 Add EXT_text loader plugin unit test
  test/EXT_text.js
  test/index.js
Labels: test
